---
title: "day 2b exercises"
author: "Emma Bea"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
# load packages ----
library(tidyverse)

# plot function f(x)=3x^2+4
#define function ----
# ctrl alt x
eq1 <- function(x) {
  3 * x^2 + 4
}


# create a data frame with range of values to evaluate our function across ----
my_data_range <- data.frame(x = c(1,100))



# plot our function as a continuous curve over our specified range of values in our data frame ----
ggplot(data = my_data_range, aes(x = x)) +
geom_function(fun = eq1)




```

```{r}
# define function ----
#f(x) = 2.4-5x^3+2.1^2


eq2 <- function(x) {
  2.4 - 5 * x^3 + 2.1 *x^2
}
my_data_range2 <- data.frame(x = c(-50,50))

ggplot(data = my_data_range2, aes (x = x)) +
geom_function(fun = eq2)

```


```{r}
# create function C(t) ----
ct <- function(t) {
  t^3
}

# find deriv of C(t)
dc_dt <- D(expr = expression(t^3), name = "t")


#store deriv as a function ----
dc_dt_fun <- function(t) {
  3 * t^2
}

# df of values ----
my_data_range <- data.frame(t=c(-5,5))





#plot function ----

ggplot(data = my_data_range, aes(x=t)) + geom_function(fun = ct, color = "red") + geom_function(fun=dc_dt_fun, color= "blue")






```


```{r}
#f(x,y,z)=2xy-3x^2z^3

f_xyz <- expression(2 *x *y -3 *x^2 * z^3)

#partial with respect to x -----

df_dx <- D(expr = f_xyz, name = "x")

df_dx



```



